### ISSUE TITLE
Migrate from jcenter ?

### ISSUE THREAD

**Issue by thegarlynch** [mlegy/red-screen-of-death#9]
If you don't know how to it is this :
https://jeroenmols.com/blog/2021/02/04/migratingjcenter/

**Comment by mlegy** [comment]
Thank you! I will take care of that in the next days.

**Comment by thegarlynch** [comment]
Is there an update yet ?

**Comment by mlegy** [comment]
I just migrated to maven.
Unfortunately I had to change the group id so to use the library now
```groovy
repositories {
  mavenCentral()
}

dependencies {
    debugImplementation 'com.mlegy.redscreenofdeath:red-screen-of-death:0.1.3'
    releaseImplementation 'com.mlegy.redscreenofdeath:red-screen-of-death-no-op:0.1.3'
}
```

Please note in the past it was `com.melegy..` now it's `com.mlegy..`
